version: '3.8'

services:
  # AI API Gateway
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-forward-api:latest
    container_name: ai-forward-api
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

