# AI API Gateway Configuration

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  driver: "sqlite"
  dsn: "./data/gateway.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s

logging:
  level: "debug"
  format: "text"
  output: "stdout"

rate_limiting:
  default_requests_per_minute: 60
  default_requests_per_hour: 1000
  default_requests_per_day: 10000

providers:
  openai:
    name: "OpenAI"
    base_url: "https://api.openai.com/v1"
    enabled: true
    priority: 1
    timeout: 30s
    retry_attempts: 3
    health_check_interval: 60s
  
  anthropic:
    name: "Anthropic"
    base_url: "https://api.anthropic.com/v1"
    enabled: true
    priority: 2
    timeout: 30s
    retry_attempts: 3
    health_check_interval: 60s

load_balancer:
  strategy: "round_robin" # round_robin, weighted, least_connections
  health_check_enabled: true
  failover_enabled: true

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_path: "/health"

billing:
  currency: "USD"
  precision: 6 # decimal places for cost calculations
  batch_size: 100 # batch size for billing record processing
