# AI API Gateway Configuration

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  driver: "sqlite"
  dsn: "./data/gateway.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s

logging:
  level: "debug"
  format: "text"
  output: "stdout"

rate_limiting:
  default_requests_per_minute: 60
  default_requests_per_hour: 1000
  default_requests_per_day: 10000

providers:
  openai:
    name: "OpenAI"
    base_url: "https://api.openai.com/v1"
    enabled: true
    priority: 1
    timeout: 30s
    retry_attempts: 3
    health_check_interval: 60s
  
  anthropic:
    name: "Anthropic"
    base_url: "https://api.anthropic.com/v1"
    enabled: true
    priority: 2
    timeout: 30s
    retry_attempts: 3
    health_check_interval: 60s

load_balancer:
  strategy: "round_robin" # round_robin, weighted, least_connections
  health_check_enabled: true
  failover_enabled: true

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_path: "/health"

billing:
  currency: "USD"
  precision: 6 # decimal places for cost calculations
  batch_size: 100 # batch size for billing record processing

# Redis配置

redis:
  # Redis服务器地址
  addr: "47.76.73.118:6379"
  # Redis密码（如果有的话）
  password: "QmpyOuWdwAHE"
  # Redis数据库编号
  db: 5
  # 连接池大小
  pool_size: 10
  # 最小空闲连接数
  min_idle_conns: 5
  # 连接超时时间
  dial_timeout: "5s"
  # 读取超时时间
  read_timeout: "3s"
  # 写入超时时间
  write_timeout: "3s"
  # 连接池超时时间
  pool_timeout: "4s"
  # 空闲连接检查频率
  idle_check_frequency: "60s"
  # 空闲连接超时时间
  idle_timeout: "5m"
  # 最大连接存活时间
  max_conn_age: "30m"

# 缓存配置
cache:
  # 是否启用缓存
  enabled: true
  # 默认过期时间
  default_ttl: "5m"
  # 用户信息缓存时间
  user_ttl: "10m"
  # API密钥缓存时间
  api_key_ttl: "15m"
  # 模型信息缓存时间
  model_ttl: "30m"
  # 提供商信息缓存时间
  provider_ttl: "30m"
  # 配额信息缓存时间
  quota_ttl: "1m"

# 分布式锁配置
distributed_lock:
  # 是否启用分布式锁
  enabled: true
  # 锁的默认过期时间
  default_ttl: "30s"
  # 获取锁的重试间隔
  retry_interval: "100ms"
  # 获取锁的最大重试次数
  max_retries: 10
