version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-forward-web
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.service=web"
      - "version=1.0.0"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local